name: List releases

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 1 */1 *'  # run every month on the first at 13:00

jobs:
  create-list:
    name: Create list of releases
    runs-on: ubuntu-latest   
    steps:      
      - name: Adding markdown
        run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY